"""align_models_with_api_contract

Revision ID: 2e60989aee55
Revises: b3c7a1d2e4f5
Create Date: 2026-03-22 00:17:01.316303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e60989aee55'
down_revision: Union[str, None] = 'b3c7a1d2e4f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_line_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fee_structure_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['fee_structure_id'], ['fee_structures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guardians',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_timeline',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('payment_id', sa.String(length=36), nullable=False),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('audit_logs', sa.Column('ip_address', sa.String(length=50), nullable=True))
    op.add_column('audit_logs', sa.Column('user_agent', sa.Text(), nullable=True))
    op.add_column('fee_structures', sa.Column('grades_json', sa.Text(), nullable=True))
    op.add_column('fee_structures', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('fee_structures', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('fee_structures', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('payments', sa.Column('channel', sa.String(length=50), nullable=True))
    op.add_column('payments', sa.Column('provider', sa.String(length=100), nullable=True))
    op.add_column('payments', sa.Column('payer_name', sa.String(length=200), nullable=True))
    op.add_column('payments', sa.Column('payer_phone', sa.String(length=50), nullable=True))
    op.add_column('payments', sa.Column('payer_email', sa.String(length=255), nullable=True))
    op.add_column('payments', sa.Column('receipt_number', sa.String(length=100), nullable=True))
    op.add_column('payments', sa.Column('currency', sa.String(length=10), nullable=False))
    op.add_column('payments', sa.Column('metadata_json', sa.Text(), nullable=True))
    op.alter_column('permissions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.add_column('reminder_configs', sa.Column('timing', sa.String(length=20), nullable=True))
    op.add_column('reminder_configs', sa.Column('channels_json', sa.Text(), nullable=True))
    op.add_column('reminder_configs', sa.Column('audience', sa.String(length=20), nullable=False))
    op.add_column('reminder_configs', sa.Column('grades_json', sa.Text(), nullable=True))
    op.add_column('reminder_configs', sa.Column('student_ids_json', sa.Text(), nullable=True))
    op.add_column('reminder_configs', sa.Column('message_template', sa.Text(), nullable=True))
    op.add_column('reminder_configs', sa.Column('days_offset', sa.Integer(), nullable=True))
    op.add_column('reminder_history', sa.Column('config_name', sa.String(length=200), nullable=True))
    op.add_column('reminder_history', sa.Column('recipient_count', sa.Integer(), nullable=False))
    op.add_column('reminder_history', sa.Column('delivered_count', sa.Integer(), nullable=False))
    op.add_column('reminder_history', sa.Column('failed_count', sa.Integer(), nullable=False))
    op.add_column('reminder_history', sa.Column('channels_json', sa.Text(), nullable=True))
    op.alter_column('reminder_history', 'student_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('roles', 'is_system',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('roles', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('roles', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.add_column('schools', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('schools', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('schools', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('schools', sa.Column('receipt_footer', sa.Text(), nullable=True))
    op.add_column('schools', sa.Column('merchant_code', sa.String(length=100), nullable=True))
    op.add_column('schools', sa.Column('biller_code', sa.String(length=100), nullable=True))
    op.add_column('schools', sa.Column('account_identifier', sa.String(length=100), nullable=True))
    op.add_column('schools', sa.Column('academic_term_config', sa.Text(), nullable=True))
    op.alter_column('schools', 'website',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('schools', 'logo_url',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.add_column('student_invoices', sa.Column('currency', sa.String(length=10), nullable=False))
    op.add_column('students', sa.Column('student_id', sa.String(length=50), nullable=True))
    op.add_column('students', sa.Column('class_name', sa.String(length=100), nullable=True))
    op.add_column('students', sa.Column('date_of_birth', sa.String(length=20), nullable=True))
    op.add_column('students', sa.Column('enrollment_date', sa.String(length=20), nullable=True))
    op.add_column('students', sa.Column('balance', sa.Float(), nullable=False))
    op.create_unique_constraint(None, 'students', ['student_id'])
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'avatar_url')
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_column('students', 'balance')
    op.drop_column('students', 'enrollment_date')
    op.drop_column('students', 'date_of_birth')
    op.drop_column('students', 'class_name')
    op.drop_column('students', 'student_id')
    op.drop_column('student_invoices', 'currency')
    op.alter_column('schools', 'logo_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
    op.alter_column('schools', 'website',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('schools', 'academic_term_config')
    op.drop_column('schools', 'account_identifier')
    op.drop_column('schools', 'biller_code')
    op.drop_column('schools', 'merchant_code')
    op.drop_column('schools', 'receipt_footer')
    op.drop_column('schools', 'country')
    op.drop_column('schools', 'state')
    op.drop_column('schools', 'city')
    op.alter_column('roles', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('roles', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('roles', 'is_system',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('reminder_history', 'student_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('reminder_history', 'channels_json')
    op.drop_column('reminder_history', 'failed_count')
    op.drop_column('reminder_history', 'delivered_count')
    op.drop_column('reminder_history', 'recipient_count')
    op.drop_column('reminder_history', 'config_name')
    op.drop_column('reminder_configs', 'days_offset')
    op.drop_column('reminder_configs', 'message_template')
    op.drop_column('reminder_configs', 'student_ids_json')
    op.drop_column('reminder_configs', 'grades_json')
    op.drop_column('reminder_configs', 'audience')
    op.drop_column('reminder_configs', 'channels_json')
    op.drop_column('reminder_configs', 'timing')
    op.alter_column('permissions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_column('payments', 'metadata_json')
    op.drop_column('payments', 'currency')
    op.drop_column('payments', 'receipt_number')
    op.drop_column('payments', 'payer_email')
    op.drop_column('payments', 'payer_phone')
    op.drop_column('payments', 'payer_name')
    op.drop_column('payments', 'provider')
    op.drop_column('payments', 'channel')
    op.drop_column('fee_structures', 'published_at')
    op.drop_column('fee_structures', 'version')
    op.drop_column('fee_structures', 'status')
    op.drop_column('fee_structures', 'grades_json')
    op.drop_column('audit_logs', 'user_agent')
    op.drop_column('audit_logs', 'ip_address')
    op.drop_table('payment_timeline')
    op.drop_table('guardians')
    op.drop_table('fee_line_items')
    # ### end Alembic commands ###
