"""add_zb_bank_tables

Revision ID: aa0aa0656797
Revises: 2fbcefcd1c6d
Create Date: 2026-03-10 18:41:56.917203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa0aa0656797'
down_revision: Union[str, None] = '2fbcefcd1c6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zb_reconciliation_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_transactions', sa.Integer(), nullable=False),
    sa.Column('matched_count', sa.Integer(), nullable=False),
    sa.Column('unmatched_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('total_amount_reconciled', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zb_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('zb_id', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.String(length=50), nullable=True),
    sa.Column('transaction_date', sa.String(length=50), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('nr1', sa.String(length=255), nullable=True),
    sa.Column('nr2', sa.String(length=255), nullable=True),
    sa.Column('nr3', sa.String(length=255), nullable=True),
    sa.Column('nr4', sa.String(length=255), nullable=True),
    sa.Column('picked', sa.String(length=50), nullable=True),
    sa.Column('tcd', sa.String(length=50), nullable=True),
    sa.Column('is_matched', sa.Boolean(), nullable=False),
    sa.Column('matched_invoice_id', sa.String(length=36), nullable=True),
    sa.Column('matched_payment_id', sa.String(length=36), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['matched_invoice_id'], ['student_invoices.id'], ),
    sa.ForeignKeyConstraint(['matched_payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zb_transactions')
    op.drop_table('zb_reconciliation_runs')
    # ### end Alembic commands ###
